name: Run Tests CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: |
                sudo apt -q update
                sudo apt upgrade -y
                sudo apt install -y \
                    curl \
                    git \
                sudo apt -qy install \
                    curl build-essential make \
                    gcc g++ intel-mkl-full \
                    libeigen3-dev \
                    freeglut3-dev \
                    python3 python3-pip python3-pytest \
                    python3-numpy python3-scipy python3-pandas
                python3 -m pip install --upgrade pip
                pip install pytest pytest-cov pybind11 PySide2 numpy scipy pytest trimesh
                pip install -r python/requirements.txt
            - name: Test
              run: |
                make test